version: "3.7"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '15432:5432'
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local