smtp:
  gmail:
    host: smtp.gmail.com
    port: 587
    user: user
    password: password
    from: mail@example.com
file:
  console:
    path: /dev/stdout
  file:
    path: ./test.txt
telegram:
  tg:
    token:

